### ISSUE TITLE
PropertyFieldListPicker context issue after upgrading to SPFx 1.12.0

### ISSUE THREAD

**Issue by dhruv-tank** [pnp/sp-dev-fx-property-controls#349] opened 2021-03-23 03:09 UTC
Type 'WebPartContext' is not assignable to type 'IWebPartContext'.
  The types of 'manifest.componentType' are incompatible between these types.
    Type 'import("C:/Users/node_modules/@microsoft/sp-module-interfaces/dist/index-internal").ComponentType' is not assignable to type 'import("C:/Users/node_modules/@pnp/spfx-property-controls/node_modules/@microsoft/sp-module-interfaces/dist/index-internal").ComponentType'.
      Type '"AdaptiveCardExtension"' is not assignable to type 'ComponentType'.ts(2322)
IPropertyFieldListPicker.d.ts(39, 5): The expected type comes from property 'context' which is declared here on type 'IPropertyFieldListPickerProps'

**Comment by AJIXuMuK** [comment] 2021-03-23 03:19
duplicate of #346.
Will be fixed in v3.

**Closed by AJIXuMuK** 2021-03-23 03:19 UTC
Labels: Needs: Triage :mag:
