### ISSUE TITLE
Incompatible with pnpjs 2.x

### ISSUE THREAD

**Issue by keith-knight** [pnp/sp-dev-fx-property-controls#414] opened 2021-12-02 06:16 UTC
#### Category
- [x] Enhancement
- [ ] Bug
- [ ] Question

#### Version

Please specify what version of the library you are using: [3.2.0]

#### Desired Behavior

Currently @pnp/spfx-property-controls still has a dependency on v1.x of pnpjs... because of this we can not upgrade our project to v2.x of pnpjs (which came out nearly 2 years ago). Can spfx-property-controls be upgraded to use pnpjs 2.x?

   `"@pnp/common": "1.3.11",
    "@pnp/logging": "1.3.11",
    "@pnp/odata": "1.3.11",
    "@pnp/sp": "1.3.11",
    "@pnp/sp-clientsvc": "1.3.11",
    "@pnp/sp-taxonomy": "1.3.11",`

**Comment by AJIXuMuK** [comment] 2021-12-02 14:30
Hello @keith-knight - I assume you can update. But the bundle size will increase as you will reference 2 separate libraries.

We're thinking on updating the reference, but for now there is a dependency on `EnterpriseTaxonomyPicker` on APIs that are not available in v2 of PnPJS.

**Comment by AJIXuMuK** [comment] 2021-12-02 14:31
Dupe of #390

**Closed** 2021-12-02 14:31 UTC
Labels: status:duplicate
