### ISSUE TITLE
PropertyFieldFilePicker - Your organisation tab, Sites tab and Upload tab is not working

### ISSUE THREAD

**Issue by muges01** [pnp/sp-dev-fx-property-controls#528] opened 2022-12-27 01:14 UTC
PropertyFieldFilePicker 

#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version
Please specify what version of the library you are using: [ 3.11.0 ]
SPFX 1.16.1

#### Expected / Desired Behavior / Question
1. The '**Recent**' tab should be displaying the recent files 
2. The '**Your Organisation**' tab should be displaying any libraries set as organization assets
3. The '**Sites**' tab should be displaying any libraries in the current site
4. The '**Upload**' tab should allow uploading the file from the local drive to the site asset library
5. The '**Upload from Link**' tab should allow external links. (**_Note_**: the 'allowExternalLinks' is set to true_)

#### Observed Behavior
1. The '**Recent**' tab - displays nothing
2. The '**Your Organisation**' tab - displays nothing
3. The '**Sites**' tab - displays nothing
4. The '**Upload**' tab - displays nothing
5. The '**Upload from Link**' tab is not accepting external link

#### Steps to Reproduce
1. Create new SPFx Webpart project using yeoman generator
2. npm i @pnp/spfx-property-controls
3. Add the following 

          PropertyFieldFilePicker("imagePicker", {
          context: this.context as any,
          filePickerResult: this.properties.imagePicker,
          onPropertyChange: this.onPropertyPaneFieldChanged.bind(this),
          properties: this.properties,
          onSave: (e: IFilePickerResult) => {
            //console.log(e);
            this.properties.imagePicker = e;
          },
          onChanged: (e: IFilePickerResult) => {
            //console.log(e);
            this.properties.imagePicker = e;
          },
          allowExternalLinks: true,
          key: "imagePickerId",
          buttonLabel: "Image Picker",
          label: "Section Image",
          }),

6. gulp build
7. gulp serve

<img width="974" alt="image" src="https://user-images.githubusercontent.com/22563887/209595593-239c27f2-2dfc-48a1-9022-a75778af9027.png">

<img width="827" alt="image" src="https://user-images.githubusercontent.com/22563887/209595567-cccc632f-2bff-446c-8ed5-e8f44c7eb4f4.png">

<img width="941" alt="image" src="https://user-images.githubusercontent.com/22563887/209595658-2d081022-3872-46b8-8923-bdd342b75402.png">

When uploading an image it will show here but nothing is saved
<img width="813" alt="image" src="https://user-images.githubusercontent.com/22563887/209595711-2204d58c-94d4-43bb-8afb-a113842328d9.png">

External links is not working
<img width="787" alt="image" src="https://user-images.githubusercontent.com/22563887/209708800-07ff96fa-c26a-47c0-b3ee-6d0c50a8159e.png">

Only the '**Stock Image**',  '**OneDrive**'  and  '**Upload from Link**'  option are working.

Thank you.

**Comment by AJIXuMuK** [comment] 2023-02-23 02:30
@muges01 - I want to clarify how the control works before digging into the issue.
1. Recent documents select documents based on a search request to the SharePoint. If the request doesn't return any items, we don't display them. **In your tests, are you seeing out of the box picker has Recent values but our control doesn't?**
2. Upload just returns a file as a result. Could you explain a bit more on "it's not saved"?
3. Upload from link supports internal links only.

For the Site and org assets - I can't repro it.

Could you please share some sort of test solution?
Also - could you check the Network trace and console logs for any errors?

Thanks.

**Comment by mbice** [comment] 2023-02-24 00:44
@AJIXuMuK I am seeing the same issue in our solution using 3.11.0 and SPFx 1.15.2. With 3.10.0 it works fine. On 3.11.0 the Recent tab is just totally blank. I find that I have to click into the blank area and then a bunch of inline styles kick in and the recent documents become visible again.

For the "Your organisation" tab, the org libraries we have configured used to show up fine, but with 3.11.0 that tab is just totally blank (no errors, just missing inline styles that would normally allow the box to show up).

e.g. 3.10.0

![image](https://user-images.githubusercontent.com/985283/221063838-71b58a84-ed3a-4796-9195-d603da248f3c.png)

3.11.0 (notice the missing inline style width of 25% on the container div, which is causing it not to show up)

![image](https://user-images.githubusercontent.com/985283/221063906-d7ef9c85-aaf1-405f-8b80-191cf68085da.png)

Same thing with the Site tab (missing inline width on the card title containers).

3.10.0

![image](https://user-images.githubusercontent.com/985283/221064065-48e1501e-6f71-40dd-aad0-7ec6519206dc.png)


3.11.0

![image](https://user-images.githubusercontent.com/985283/221064038-18be515c-3404-4bf2-be5d-c63e7b05579b.png)

Hope that helps!

**Comment by muges01** [comment] 2023-02-25 15:08
Hi @AJIXuMuK, 
I do have documents in the SharePoint. I agree with @mbice, that actual scenario, I hope that helps. 
Thank you.

**Comment by AJIXuMuK** [comment] 2023-02-25 15:19
I'll try to repro it again. 
Thanks for details!

**Comment by AJIXuMuK** [comment] 2023-03-12 23:12
@muges01 @mbice  - I made changes to the requests.
The changes are available in the latest beta version.

Could you please check on your side if there are still any errors?

Thanks!

**Comment by c-eiser13** [comment] 2023-03-17 21:13
@AJIXuMuK I was having the same issue with the FilePicker in the reusable controls project and the latest version fixed the site tab, and I submitted a fix for the Recent tab, which was still not working correctly. 

It was reported to me today that the property control file picker was behaving the same, so I found this thread, installed the beta, and it still does not work for me. My experience is, when I click Recent or Site, you see the spinner when it attempts to fetch data, but only see a white screen. If I resize the window the underlying list control will then render properly. Here is an example:
![filepickerissue](https://user-images.githubusercontent.com/42096464/226050750-cd2c5420-b5db-42e0-a858-ec9d724da5e6.gif)

![image](https://user-images.githubusercontent.com/42096464/226051131-19cf2e4c-c58e-428f-9154-eb899aba0eaa.png)

Let me know if I can provide any further info to assist. Thanks!

**Comment by mbice** [comment] 2023-03-18 23:05
@AJIXuMuK same here (just re-tested with latest 3.13.0-beta.4457085) and the issue still reproduces. Both recent and sites panels are blank. If I resize the viewport, some inline styles kick in and content becomes visible again.

**Comment by AJIXuMuK** [comment] 2023-03-19 01:43
Finally, I was able to repro it and fix it.
Please, check the latest `beta` - should be good for all tabs

**Comment by mbice** [comment] 2023-03-19 14:59
@AJIXuMuK tested against latest beta and the tabs are looking good for me. Thanks for this fix, really appreciate it!

**Comment by muges01** [comment] 2023-03-26 21:15
Ok I'll retry the beta version and reply to this forum by 28/03/2023. Thank you

**Comment by muges01** [comment] 2023-03-27 23:23
Yes, I have tested with the latest beta version and all the tabs are working correctly. Thank you. 

When this changes will be in GA?

**Comment by bhoomesh-spe** [comment] 2023-04-05 15:09
HI @AJIXuMuK @mbice 

I have tried with beta version but still facing an issue.

I have used below version in my app
"@microsoft/sp-core-library": "1.16.0",
"@pnp/spfx-property-controls": "^3.13.0-beta.4458261",

Only 3 tabs are working as expected.

- Recent
- Stock Images
- From a link

In site tab when I tried to click on any of folder like Documents or Site Assets, the property pane control is automatically close.

Please check attached screenshot for the same.

<img width="960" alt="Error" src="https://user-images.githubusercontent.com/99523338/230123956-b0b9087d-63fb-44e5-9aae-6a0f475d02c8.png">

**Comment by AJIXuMuK** [comment] 2023-04-05 15:16
It seems to be a separate issue. 
Please create a new one.

**Comment by bhoomesh-spe** [comment] 2023-04-05 15:34
Hi @AJIXuMuK 

i didn't get you. Can you please explain in details?

**Comment by AJIXuMuK** [comment] 2023-04-05 15:47
@bhoomesh-spe The problem discussed here is about the tiles being invisible in some tabs. 
Your problem is about clicking a tile which is a logically separate one. 
I'm asking you to open a new GitHub issue for your problem to track/fix it properly.

**Comment by bhoomesh-spe** [comment] 2023-04-05 15:50
Hi @AJIXuMuK

Thanks for quick response.

I will create new issue for tiles issue. But upload image from local machine functionality is not working. 

Can you please check that upload tab issue in current issue?

Thanks

**Comment by joelfmrodrigues** [comment] 2023-07-18 10:51
Fixed, closing

**Closed by joelfmrodrigues** 2023-07-18 10:51 UTC
Labels: status:fixed-next-drop

**Comment by bhoomesh-spe** [comment] 2023-07-18 11:10
@joelfmrodrigues - Thanks for fixing the issue. Can you please let me know in which version the new changes will be available?

**Comment by joelfmrodrigues** [comment] 2023-07-18 11:43
Hi @bhoomesh-spe , I was referring to the initial issue, as per Alex's suggestion, please test the latest version released today and open a separate issue if you still find problems. Sorry but we need to try to avoid chained discussions as this makes following up really hard
