### ISSUE TITLE
Setting ViewType to "tiles" for PropertyFieldFilePicker makes the field unusable

### ISSUE THREAD

**Issue by gakowalski** [pnp/sp-dev-fx-property-controls#562] opened 2023-04-19 08:16 UTC
#### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question

#### Version

3.12.0 (latest official)
3.13.0-beta.4458307 (latest beta)

#### Expected / Desired Behavior / Question

User can change view type by clicking on a button in top-right corner, selecting "Tiles" view and then browse and select files in this view mode.

#### Observed Behavior

After selecting "Tiles" view, dialog window/pane is abpruptly closed, property field disappears from property pane and is made inaccesible. After page refresh property field is shown again but clicking on "Choose image" link removes it again without showing anything and without giving user possibility to change view mode.

In the browser console this error message appears:

> Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=Tue%20Feb%2014%202023%2014%3A10%3A45%20GMT%2B0100%20(czas%20%C5%9Brodkowoeuropejski%20standardowy) for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

The ONLY way for the user to regain possibility of using file picker again is to manually run Javascript code in the console to clear local storage data cell with selected vew mode:

```
localStorage.removeItem('comparerSiteFilesLayout');
```

#### Steps to Reproduce

1. Make a webpart using PropertyFieldFilePicker property field, deploy it.
2. In page edit mode, click "Choose image".
3. In top-right corner click view mode button and select tiles from the dropdown menu.

**Comment by joelfmrodrigues** [comment] 2023-11-22 21:21
Many thanks @ClemSK , the PR was merged and the fix should be available in the beta release within a few minutes.
Could you please test and let us know if the issue is resolved?

**Comment by ClemSK** [comment] 2023-11-23 14:15
No probs @joelfmrodrigues, I've tested the beta release and it seems resolved from our side.

**Closed** 2023-11-25 19:14 UTC
Labels: status:fixed-next-drop, type:bug

**Comment by germain-italic** [comment] 2024-10-31 16:48
I'm having the same problem with 4.0.0-beta.6059131

The temp solution suggested by @gakowalski works

@ClemSK any plans to implement the durable fix in 4.x?
